config/routes.rb
ShopifyTest::Application.routes.draw do
  match 'welcome'            => 'home#welcome'

  match 'design'             => 'home#design'

  match 'login'              => 'login#index',        :as => :login

  match 'login/authenticate' => 'login#authenticate', :as => :authenticate

  match 'login/finalize'     => 'login#finalize',     :as => :finalize

  match 'login/logout'       => 'login#logout',       :as => :logout

  root :to                   => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  around_filter :shopify_session, :except => 'welcome'
  
  def welcome
    current_host = "#{request.host}#{':' + request.port.to_s if request.port != 80}"
    @callback_url = "http://#{current_host}/login/finalize"
  end
  
  def index
    # get 5 products
    @products = ShopifyAPI::Product.find(:all, :params => {:limit => 10})

    # get latest 5 orders
    @orders   = ShopifyAPI::Order.find(:all, :params => {:limit => 5, :order => "created_at DESC" })
  end
  
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
    # Ask user for their #{shop}.myshopify.com address
    
    # If the #{shop}.myshopify.com address is already provided in the URL, just skip to #authenticate
    if params[:shop].present?
      redirect_to authenticate_path(:shop => params[:shop])
    end
  end

  def authenticate
    if params[:shop].present?
      redirect_to ShopifyAPI::Session.new(params[:shop].to_s.strip).create_permission_url
    else
      redirect_to return_address
    end
  end
  
  # Shopify redirects the logged-in user back to this action along with
  # the authorization token t.
  # 
  # This token is later combined with the developer's shared secret to form
  # the password used to call API methods.
  def finalize
    shopify_session = ShopifyAPI::Session.new(params[:shop], params[:t], params)
    if shopify_session.valid?
      session[:shopify] = shopify_session
      flash[:notice] = "Logged in to shopify store."
      
      redirect_to return_address
      session[:return_to] = nil
    else
      flash[:error] = "Could not log in to Shopify store."
      redirect_to :action => 'index'
    end
  end
  
  def logout
    session[:shopify] = nil
    flash[:notice] = "Successfully logged out."
    
    redirect_to :action => 'index'
  end
  
  protected
  
  def return_address
    session[:return_to] || root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/login_helper.rb
module LoginHelper  
  
end

app/helpers/tabs_helper.rb
module TabsHelper
  
  def active_nav_class(name, action = nil)
    if action.present?
      return if controller.action_name != action
    end
    
    'active' if controller.controller_name =~ /#{name}/i
  end
  
end

app/views/home/index.html.erb
<header class="jumbotron">
  <div class="inner">
    <div class="container">
      <h1 style="letter-spacing:-3px; margin-bottom:20px;">Where do I start?</h1>
      <p class="lead">An <strong>intro</strong> to using the Shopify App Template<br/>
      including information on the <strong>Shopify API</strong> and <strong>Bootstrap,</strong><br/>
      just to get the ball rolling.</p>
    </div><!-- /container -->
  </div>
</header>

<div class="row">
  <div class="span3">
    <div class="well">  
      <h3>Check out the <code>home_controller</code></h3>
      <hr style="margin:2px 0 7px"/>
      <p>The controller in this demo application fetches the newest 5 orders and products and makes them available as instance variables <code>@orders</code> and <code>@products</code></p>
    
      <br/>
    
      <h3>Take a look at <code>index.html.erb</code></h3>
      <hr style="margin:2px 0 7px"/>
      <p>Index is the Ruby template you are currently viewing. Have a look at the markup and Ruby code to see how the Shopify API is being used. It's located at <code>views/home/index.html.erb</code></p>
    </div>
    
    <h3>Additional Docs</h3>
    <p>You can become an expert pretty quickly by reading up on these docs:</p>
    
    <ul>
      <li>
        <%= link_to 'API documentation', 'http://www.shopify.com/developers/api/' %>
        <span class="note">Learn what you can do with the Shopify API</span>
      </li><br/>
      <li>
        <%= link_to 'Bootstrap documentation', 'http://twitter.github.com/bootstrap/' %>
        <span class="note">Find out what you can do with Twitter Bootstrap</span>
      </li><br/>
      <li>
        <%= link_to 'Wiki', 'http://wiki.shopify.com/' %>
        <span class="note">Get more information and share your knowledge</span>
      </li><br/>
      <li>
        <%= link_to 'Forum', 'http://forums.shopify.com/community' %>
        <span class="note">Ask questions and see what others already wanted to know</span>
      </li>
    </ul>
  
    <hr/>
  
    <h3>Once you're ready</h3>
  
    <p>We'd love to see what you create using the Shopify API. You can keep up to date on the latest and greatest via the <%= link_to 'Shopify API Twitter Account', 'http://www.twitter.com/shopifyapi' %>. You can also read the latest information on the <%= link_to 'API Publishing Page', 'http://www.shopify.com/developers/publishing/' %>.</p>
    
    <br/>
    
    <a href="https://twitter.com/shopifyapi" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @shopifyapi</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </div> <!-- span3 / left-column -->


  <div class="span8 offset1">
    <h2>Recent orders</h2>
  
    <% if @orders.blank? %>
      <table class="table table-striped">
        <tr>
          <td><em>There are no orders in your store.</em></td>
        </tr>
      </table>
    
    <% else %>
  
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Order</th>
            <th>Placed by</th>
            <th>Paid</th>
            <th>Fulfillment</th>
            <th>Total</th>
          </tr>
        </thead>
      <% @orders.each do |order| %>
        <tr>
          <td><%= link_to order.name, "https://#{current_shop.url}/admin/orders/#{order.id}", :target => 'blank' %></td>
          <td><%= order.billing_address.name %></td>
          <td>
            <span class="label  <% if order.financial_status  == 'paid' %>label-success<% end %> <% if order.financial_status  == 'pending' %>label-warning<% end %> <% if order.financial_status  == 'refunded' %>label-important<% end %>"><%= order.financial_status %>
            </span>
          </td>
          <td>
            <% if !order.fulfillment_status %>
            <span class="label">Not Fulfilled</span>
            <% else %>
            <span class="label label-success">Fulfilled</span>
            <% end %>
          </td>
          <td><%= order.total_price %> <%= order.currency %></td>
        </tr>
      <% end %>
      </table>
      
    <% end %>
    
    <br/>
    
    <h2>New Products</h2>
    
    <div class="accordion" id="accordion">      
      
      <% if @products.blank? %>
      
        <div class="accordion-group">
          <div class="accordion-heading">
            <em>There are no products in your store.</em>
          </div>
        </div>
      
      <% else %>
      
        <%  @products.each_with_index do |product, index| %>
          <div class="accordion-group">
            <div class="accordion-heading">
              
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#<%= product.id %>">
                <%= product.title %> <span class="pull-right muted"><%= product.price_range %> <%= current_shop.shop.currency %></span>
              </a>
            </div>
        
            <div id="<%= product.id %>" class="accordion-body collapse <% if index == 1 %>in<% end %>">
              <div class="accordion-inner">
                
                <% if !product.images.empty? %>
                  <div class="polaroid">
                    <%= link_to image_tag(product.images.first.medium), '#modal-'+product.id.to_s, :'data-toggle' => 'modal' %>
                  </div>
                <% end %>
                
                <p><strong>Type:</strong> <%= product.product_type %></p>
                <p><strong>Vendor:</strong> <%= product.vendor %></p>
                <p><%= raw(product.body_html) %></p><br/>
                <% if product.published_at != nil %>
                <p class="muted">Published at <%= Time.parse(product.published_at).strftime("%H:%M on %m/%d/%Y") %></p>
                <% end %>
                <p><%= link_to raw('View in your Shopify Admin <i class="icon-chevron-right" style="opacity:.25"></i>'), "https://#{current_shop.url}/admin/products/#{product.id}", :target => 'blank', :class => 'btn btn-primary' %></p>
              </div>
              
            </div>
          </div>
          
          <div class="modal hide fade" id="modal-<%= product.id %>" style="display:none;">
            <div class="modal-header">
              <a class="close" data-dismiss="modal">×</a>
              <h3><%= product.title %></h3>
            </div>
            <div class="modal-body" >
              <% if !product.images.empty? %>
                <%= image_tag product.images.first.large %>
              <% end %>
            </div>
          </div>
        <% end %>
      
      <% end %>
      
    </div> <!-- accordion -->
  </div> <!-- span8 / right-column -->
</div>

app/views/home/welcome.html.erb
<h1 class="green">Welcome</h1>

<p>
  This is an example Shopify application that shows what you can do with the Shopify API.
</p>

<div class="info" style="clear: both">
  This will send the <strong>API-Key</strong> and <strong>Secret</strong> to a shop, and make sure that you have the rights to 
  access its private admin data.<br/>
  After authenticating, you will be redirected to the <code>finalize</code> action of your <code>LoginController</code>, which stores the session, and then redirects you to your example dashboard.<br/>
  Your <code>HomeController</code> will get your recent <code>Orders</code> and <code>Articles</code> through the 
  Shopify <%= link_to 'REST', 'http://www.xfront.com/REST-Web-Services.html', :title => "Get more information about REST web services in general" %> API and list them with all of your <code>Products</code>.
  You can click on a link of one of your objects and will then be taken to the corresponding admin area of your shop.<br/>

  <p><strong>Note:</strong> There are no examples for <em>creating or editing</em> objects, but you are also able to do that with the Shopify API!</p>
</div>

<h3>1. Make sure you've entered a valid <em>API-Key</em> and <em>Secret</em></h3>

<ul style="list-style-type: lower-alpha;">
  <li>
    <p>
      If you haven't registered your application yet, then enter your shop's <strong>URL</strong> or <strong>subdomain</strong> here:<br/>
    </p>
    
    <div class="box grey" style="width: 500px;text-align: center">
      <script type="text/javascript" charset="utf-8">
        function getApiUrl() {
          var name = $('shop').value; 
          if (name.indexOf('.') == -1) {
            var api_url = name + '.myshopify.com';
          } else {
            var api_url = name.replace(/^https?:\/\//, ''); // Remove the "http://"
          }
          api_url = api_url.replace(/\/$/, ''); // Trim trailing slashes
          $('api-form').action = 'http://' + api_url + '/admin/api_clients/new';
        }
      </script>
      
      <% form_tag '', :method => 'get', :id => 'api-form', :onsubmit => "getApiUrl(); return true;", :style => 'margin-left: 16px;' do %>
        <%= text_field_tag 'shop', '', :size => 40 %>
        <%= hidden_field_tag 'api_client[return_url]', @callback_url %>
        <%= submit_tag 'Get API key' %>
      <% end %>
    </div>

    <p>
      After registering your application with Shopify, you need to edit the <code>config/shopify.yml</code> file,
      and insert your <em>API-Key</em> and <em>Secret</em> there. Then restart this application.
    </p>
  </li>
  <li>
    <p><strong>If you've already supplied those to the generator</strong>, then move on to <%= link_to 'Step #2', '#callback-step' %>.</p>
  </li>
</ul>

<h3 id="callback-step">2. Make sure your <em>callback URL</em> is correct</h3>

The URL should be <code><%= @callback_url %></code>, 
with the host portion of the URL pointing to whichever domain is currently hosting this application. <br/> 
The callback URL of your app can be changed in the API screen of your Shopify admin interface.

<h3>3. <%= link_to 'Login', '/login' %> to your shop</h3>

<div class="border-wrap">
  <div class="info">
    This will send the <strong>API-Key</strong> and <strong>Secret</strong> to a shop, and make sure that you have the rights to 
    access its private admin data.<br/>
    After authenticating, you will be redirected to the <code>finalize</code> action of your <code>LoginController</code>, which stores the session, and then redirects you to your example dashboard.<br/>
    Your <code>HomeController</code> will get your recent <code>Orders</code> and <code>Articles</code> through the 
    Shopify <%= link_to 'REST', 'http://www.xfront.com/REST-Web-Services.html', :title => "Get more information about REST web services in general" %> API and list them with all of your <code>Products</code>.
    You can click on a link of one of your objects and will then be taken to the corresponding admin area of your shop.<br/>
    
    <p><strong>Note:</strong> There are no examples for <em>creating or editing</em> objects, but you are also able to do that with the Shopify API!</p>
  </div>
</div>

<h3>4. Check out the source code of the <code>home_controller</code> and its <code>index</code> template</h3>

<p class="description">
  You can analyze those files to see how the ShopifyAPI is used and get a glimpse of what's possible.
</p>

<h3>5. Read additional documentation</h3>

<p class="description">
  Become an expert.
</p>

<ul>
  <li>
    <%= link_to 'API documentation', 'http://www.shopify.com/developers/api' %>
    <span class="hint">(An overview of what you can do with the Shopify API.)
  </li>
  <li>
    <%= link_to 'Wiki (needs its own API section)', 'http://wiki.shopify.com/' %>
    <span class="hint">(Get more information and share your knowledge.)
  </li>
  <li>
    <%= link_to 'Forum (needs its own API section)', 'http://forums.shopify.com/community' %>
    <span class="hint">(Ask questions and see what others already wanted to know.)
  </li>
</ul>

<h3>6. Publish your application</h3>

<p class="description">
  This feature is not implemented yet, but it in the future it will allow you to register your application, 
  so that will be shown in a public directory with a description, so that more users will take notice of it.
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Shopify Demo App</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  
  <!-- icons -->
  <link rel="shortcut icon" href="../assets/favicon.png">
  <link rel="apple-touch-icon" href="../assets/shopify-57.png">
  <link rel="apple-touch-icon" sizes="72x72" href="../assets/shopify-72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="../assets/shopify-114.png">
  
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>

<body>
  
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        
        <%= link_to 'Shopify Demo App', '/', :class => 'brand' %>
        
        <% if current_shop %>
          <div class="nav-collapse">
            <ul class="nav">
              <li class='<%= active_nav_class('home', 'index') %>'><%= link_to 'Where to Start', '/' %></li>
              <li class='<%= active_nav_class('home', 'design') %>'><%= link_to 'Bootstrap Info', '/design' %></li>
            </ul>
          </div>
          
          <ul class="nav pull-right">
            <li class="dropdown">
              <%= link_to raw(current_shop.url+' <b class="caret"></b>'), "https://#{current_shop.url}", :class => 'shop_name dropdown-toggle', :'data-toggle' => 'dropdown'  %>
              <ul class="dropdown-menu">
                <li><%= link_to raw('<i class="icon-home"></i> Storefront'), "http://"+current_shop.url, :target => 'blank' %></li>
                <li><%= link_to raw('<i class="icon-cog"></i> Shopify Admin'), "http://"+current_shop.url+"/admin", :target => 'blank' %></li>
                <li class="divider"></li>
                <li><%= link_to raw('<i class="icon-off"></i> logout'), logout_path %></li>
              </ul>
            </li>
          </ul>
        <% end %>
        
      </div>
    </div>
  </div>
  
  
  <div class="container">
    
    <div class="content">
      <%= yield %>
    </div>
    
    <footer>
      <p>A Shopify app by (company name here)</p>
    </footer>
    
  </div> <!-- /container -->
</body>
</html>

app/views/login/index.html.erb
<div class="page-header" id="login-header">
  <h1>Install This App</h1>
  <h1><small>This app requires you to login to start using it.</small></h1>
</div>

<div style="width:340px; margin:0 auto;">
  <%= form_tag '/login/authenticate', :class => 'form-search' do %>
    <%= text_field_tag 'shop', nil, :placeholder => 'Shop URL', :class => 'btn-large' %>
    <%= submit_tag 'Install', :class => 'btn btn-primary btn-large' %>
  <% end %>
</div>

<p align="center" style="margin-top:30px">
  <%= image_tag '../assets/shopify.png' %>
</p>

<br/>

<p align="center" class="muted">
  Don't have a shop? <a href="https://app.shopify.com/services/partners/api_clients/test_shops">Create a Test Shop</a>
</p>